language: python
sudo: required
dist: xenial
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7' # https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
  - 'pypy'
  - 'pypy3.5'
install:
  - pip install coveralls
  - pip install tox-travis
script:
  - tox
notifications:
  email:
    on_success: never
    on_failure: always
after_success: coveralls
