language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - 'pypy'
  #- 'pypy3.5'
matrix:
  include:
    - python: '3.7'
      dist: xenial
      sudo: true
install:
  - pip install --upgrade pip
  - pip install coveralls
  - pip install tox-travis
script:
  - tox
notifications:
  email:
    on_success: never
    on_failure: always
after_success: coveralls
