language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
 # - '3.7' --> https://github.com/travis-ci/travis-ci/issues/9815
  - 'pypy2.7-5.10.0'
 # - 'pypy3.5-5.10.1' --> https://github.com/tox-dev/tox-travis/issues/114
install:
  - pip install coveralls
  - pip install tox-travis
script:
  - tox
notifications:
  email:
    on_success: never
    on_failure: always
after_success: coveralls
