language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
 # - '3.7'
install:
  - pip install coveralls
  - pip install tox-travis
script:
  - tox
notifications:
  email:
    on_success: never
    on_failure: always
after_success: coveralls