environment:
  matrix:
  - TOXENV: py35
  - TOXENV: py36
  - TOXENV: py37
  - TOXENV: py38

build: off

install:
  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  - ps: python -Wignore -m pip install --upgrade pip --user
  - ps: python -Wignore -m pip install tox --user

  - ps: python -Wignore -m pip install pipenv --user
  - ps: rm Pipfile.lock
  - ps: $PIPENV_QUIET="true"
  - ps: python -Wignore -m pipenv install --dev

test_script:
  - tox
