version: 2
jobs:
  build:
    branches:
      only:
        - master
        - develop
        - circleci
    docker:
      - image: themattrix/tox
        environment:
          PIPENV_VENV_IN_PROJECT: true

    working_directory: ~/dhis2py

    steps:
      - checkout

      - run:
          command: |
            pip install --upgrade pip
            pip install tox codecov

      - run:
          name: run tests
          command: |
            tox
      - run:
          name: send coverage
          command: |
            codecov