version: 2
jobs:
  build:
    branches:
      only:
        - master
        - dev
    docker:
      - image: themattrix/tox
        environment:
          PIPENV_VENV_IN_PROJECT: true

    working_directory: ~/dhis2py

    steps:
      - checkout

      - run:
          name: install pip, tox, codecov
          command: |
            pip install --upgrade pip
            pip install tox codecov pathlib2

      - run:
          name: run unit tests
          command: |
            tox
      - run:
          name: send code coverage
          command: |
            codecov
