version: 2
jobs:
  build:
    branches:
      only:
        - master
        - develop
        - circleci
    docker:
      - image: themattrix/tox
        environment:
          PIPENV_VENV_IN_PROJECT: true

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install pipenv and dependencies
          command: |
            pip install --upgrade pip
            pip install pipenv tox
            pipenv install --dev

      - run:
          name: run tests
          command: |
            tox
